import React from "react";

const Head = () => {
  return (
    <>
      <title>BookIt</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta content="Generated by create next app" name="description" />
      <link href="/favicon.ico" rel="icon" />
    </>
  );
};

export default Head;
